### ISSUE TITLE
Authentication / Creating token does not work

### ISSUE THREAD

**Issue by araeubig** [artnum/BizCuit-Bexio#1]
Do you have get a working token creation via GitHub codespaces?

I tried the bexio example and tried the https://github.com/onlime/bexio-api-client way - i only get in both cases:
"Irgendetwas ist schiefgelaufen.
Die mitgegebene Redirect-URI wird nicht unterstützt."

Do you have any hints for me?

Regards André

**Comment by araeubig** [comment]
I solved it - sorry for disturbing. -> The bexio documentation is not bad but could be more user-friendly.....

**Comment by araeubig** [comment]
I was a little bit confused on the right authentication - but you solved it with a fixed "internal" API-token and that seems to work now.

**Comment by araeubig** [comment]
It works now perfect with the "standard" API-Token generated inside the bexio-Backend. SOLVED

**Comment by artnum** [comment]
Yes the token must come from Bexio directly.
