### ISSUE TITLE
BexioQuote: get doesn't work

### ISSUE THREAD

**Issue by araeubig** [artnum/BizCuit-Bexio#10]
```
$bxquote = new BizCuit\BexioQuote($bxCtx);
$id = 5;
$quote = $bxquote->get($id);
```
It runs into:
`Fatal error: Uncaught Exception: {"error_code":415,"message":"Could not parse the data."} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:153 Stack trace: #0 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(217): BizCuit\BexioCTX->handle_result('{"error_code":4...', 415, 'application/jso...') #1 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(497): BizCuit\BexioCTX->fetch() #2 /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php(175): BizCuit\BexioQuote->get(5) #3 {main} Next Exception: The data could not be processed or the accept header is invalid in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 153 Exception: The data could not be processed or the accept header is invalid in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 153 Call Stack: 0.0004 487048 1. {main}() /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php:0 0.2435 604824 2. BizCuit\BexioQuote->get($id = 5, $options = ???) /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php:175 0.2435 604960 3. BizCuit\BexioCTX->fetch() /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:497 0.3802 601344 4. BizCuit\BexioCTX->handle_result($data = '{"error_code":415,"message":"Could not parse the data."}', $code = 415, $type = 'application/json') /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:217 Nested Exceptions: Exception: {"error_code":415,"message":"Could not parse the data."} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 153 Call Stack: The stack is empty or not available`

**Comment by artnum** [comment]
Isn't the same issue as #3 ? As "Could not parse the data" was the same error message and I tested and had no issue.

**Comment by araeubig** [comment]
I will make the new test tomorrow morning.

**Comment by araeubig** [comment]
Trying to get a quote gets me the same error like getting a contact. I think i do anything wrong but don't know what actual,

I found out that

```
$bxquote = new BizCuit\BexioQuote($bxCtx);
$id = 157;
$quote = $bxquote->get($id);
```

if the quote really doesn't exists (using a non existent id):
`/workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php:206: bool(false) Fatal error: Uncaught Exception: {"error_code":404,"message":"Page not found"} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:151 Stack trace: #0 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(217): BizCuit\BexioCTX->handle_result('{"error_code":4...', 404, 'application/jso...') #1 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(497): BizCuit\BexioCTX->fetch() #2 /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php(279): BizCuit\BexioQuote->get(158) #3 {main} Next Exception: The resource could not be found in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 151 Exception: The resource could not be found in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 151 Call Stack: 0.0006 480072 1. {main}() /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php:0 1.0813 598280 2. BizCuit\BexioQuote->get($id = 158, $options = ???) /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php:279 1.0813 598424 3. BizCuit\BexioCTX->fetch() /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:497 1.2088 594800 4. BizCuit\BexioCTX->handle_result($data = '{"error_code":404,"message":"Page not found"}', $code = 404, $type = 'application/json') /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:217 Nested Exceptions: Exception: {"error_code":404,"message":"Page not found"} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 151 Call Stack: The stack is empty or not available `

if the quote exists (using an existent id):
`/workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php:206: bool(false) Fatal error: Uncaught Exception: {"error_code":415,"message":"Could not parse the data."} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:153 Stack trace: #0 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(217): BizCuit\BexioCTX->handle_result('{"error_code":4...', 415, 'application/jso...') #1 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(497): BizCuit\BexioCTX->fetch() #2 /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php(279): BizCuit\BexioQuote->get(1) #3 {main} Next Exception: The data could not be processed or the accept header is invalid in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 153 Exception: The data could not be processed or the accept header is invalid in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 153 Call Stack: 0.0004 509136 1. {main}() /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php:0 1.1010 627344 2. BizCuit\BexioQuote->get($id = 1, $options = ???) /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php:279 1.1010 627480 3. BizCuit\BexioCTX->fetch() /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:497 1.2314 623864 4. BizCuit\BexioCTX->handle_result($data = '{"error_code":415,"message":"Could not parse the data."}', $code = 415, $type = 'application/json') /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:217 Nested Exceptions: Exception: {"error_code":415,"message":"Could not parse the data."} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 153 Call Stack: The stack is empty or not available`

**Comment by araeubig** [comment]
It works perfect - I don't know why it hasn't but after coding in new file all absolutely perfect.
