### ISSUE TITLE
Your function toJson ......

### ISSUE THREAD

**Issue by araeubig** [artnum/BizCuit-Bexio#14]
I think your embedded functions are used for the communication with the API. Is that right? Actually i try to convert the result of a "list"- and "search"-query to reduced JSON.

**Comment by artnum** [comment]
Can you be more specific about what you need ?

**Comment by araeubig** [comment]
I try to make some tests and need the result as json to try some things.

The result of a query looks like this:
```
[0] => BizCuit\BXObject\Contact Object
        (
            [changes:protected] => Array
                (
                )

            [content:protected] => stdClass Object
            .......
```

and i need only the real array content of the stdClass Object. I tried to convert it by it doesnt work like expected - therefore my question if there is a built in function to get only the real content without the objects.

**Comment by artnum** [comment]
For BXObject there is no way, yet, to get the content. But it would be easy to create such function.

**Comment by araeubig** [comment]
Absolutely - for my tests it's done with:
```
$contacts = new BizCuit\BexioContact($bxCtx);
$contactsQuery = $contacts->newQuery();
$contactsresult = $contacts->list($order_by="name_1");
foreach ( $contactsresult as $contact) {
    $temp = (array) getProtectedValue($contact, 'content');
    $data[] =  $temp;
} 
```
After that reconverted to clean JSON for testing. Perfect.

Actually i run into a lot of errors with my second testing setup in codespaces........ (not so easy to run React as frontend and PHP as backend in the same codespace - i think about searching a cloud solution for testing the api which could be updated over github - if you have an idea it would be welcome).

Regards and a nice evening André
