### ISSUE TITLE
Error in using "list()" with BexioSalutation

### ISSUE THREAD

**Issue by araeubig** [artnum/BizCuit-Bexio#15]
I tried using "list()" with **'BexioSalutation'** but it gives my following error:

`Fatal error: Uncaught Exception: {"error_code":400,"message":"The following order parameters could not have been applied: ","errors":["id"]} in /workspaces/bexio-POS-App/www/vendor/artnum/bizcuit-bexio/bexio.php:148 Stack trace: #0 /workspaces/bexio-POS-App/www/vendor/artnum/bizcuit-bexio/bexio.php(217): BizCuit\BexioCTX->handle_result('{"error_code":4...', 400, 'application/jso...') #1 /workspaces/bexio-POS-App/www/vendor/artnum/bizcuit-bexio/bexio.php(445): BizCuit\BexioCTX->fetch() #2 /workspaces/bexio-POS-App/www/contacts.php(16): BizCuit\BexioSalutation->list() #3 {main} Next Exception: The request parameters are invalid in /workspaces/bexio-POS-App/www/vendor/artnum/bizcuit-bexio/bexio.php:148 Stack trace: #0 /workspaces/bexio-POS-App/www/vendor/artnum/bizcuit-bexio/bexio.php(217): BizCuit\BexioCTX->handle_result('{"error_code":4...', 400, 'application/jso...') #1 /workspaces/bexio-POS-App/www/vendor/artnum/bizcuit-bexio/bexio.php(445): BizCuit\BexioCTX->fetch() #2 /workspaces/bexio-POS-App/www/contacts.php(16): BizCuit\BexioSalutation->list() #3 {main} thrown in /workspaces/bexio-POS-App/www/vendor/artnum/bizcuit-bexio/bexio.php on line 148 `

I used basic "list()" without any parameters.

For
**'BexioTitle'
'BexioCountry'
'BexioContactGroup'
'BexioContact'**
it works perfect.

**Comment by artnum** [comment]
BexioSalutation is still based on a ROObject. It means I haven't tested and created a specific object for the endpoint. Bexio has many bugs and quirks (for example you can create a perfectly valid swiss qr bill that couldn't be loaded into Bexio, they limited some fields shorter than the standard).

So ROObject are endpoints I haven't dealt with yet and didn't work out the workarounds if needed. ROObject might work but may not.

It can be a bug in my code, I don't exclude that either. I will check that, but when dealing with endpoints still based on ROObject, you better implements them instead on relying on them.

**Comment by artnum** [comment]
I just tested with the following

```php
$bx = new BexioCTX($token); 
$salutation = new BizCuit\BexioSalutation($bx);
var_dump($salutation->list());
```

And I get 

```
array(4) {
  [0] =>
  class BizCuit\BXObject\Salutation#23 (2) {
    protected array $changes =>
    array(0) {
    }
    protected stdClass $content =>
    class stdClass#24 (2) {
      public $id =>
      int(1)
      public $name =>
      string(4) "Herr"
    }
  }
  [1] =>
  class BizCuit\BXObject\Salutation#25 (2) {
    protected array $changes =>
    array(0) {
    }
    protected stdClass $content =>
    class stdClass#26 (2) {
      public $id =>
      int(2)
      public $name =>
      string(4) "Frau"
    }
  }
  [2] =>
  class BizCuit\BXObject\Salutation#27 (2) {
    protected array $changes =>
    array(0) {
    }
    protected stdClass $content =>
    class stdClass#28 (2) {
      public $id =>
      int(3)
      public $name =>
      string(7) "Familie"
    }
  }
  [3] =>
  class BizCuit\BXObject\Salutation#29 (2) {
    protected array $changes =>
    array(0) {
    }
    protected stdClass $content =>
    class stdClass#30 (2) {
      public $id =>
      int(4)
      public $name =>
      string(11) "Herr & Frau"
    }
  }
}
```
Do you follow the master branch ?

**Comment by araeubig** [comment]
Yes (respectively i made a sync before) - i will test it until today evening.

**Comment by artnum** [comment]
My bad, I found a bug, list() didn't reset the method to get, so I you modify something before, it will do the request with post or put. Fixed now
