### ISSUE TITLE
Missing sample

### ISSUE THREAD

**Issue by araeubig** [artnum/BizCuit-Bexio#2]
I have read through your repo and started reading your documentation. My first thoughts are, that you made a great extendable work -> this is really sustainable. But i'm missing a more detailed simple example including the authentication - i mean a working example would be perfect.

Regards André

**Comment by araeubig** [comment]
The authentication problem is solved by now but i tried your basic example again but i get an error code 400 - please provide a working example or let me know what to do.

Fatal error: Uncaught Exception: {"message":"status: unsupported value type","error_code":400} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:148 Stack trace: #0 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(217): BizCuit\BexioCTX->handle_result('{"message":"sta...', 400, 'application/jso...') #1 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(335): BizCuit\BexioCTX->fetch() #2 /workspaces/bexio-stripe-pos-backend/www/bexio/test.php(14): BizCuit\BexioBills->search(Object(stdClass)) #3 {main} Next Exception: The request parameters are invalid in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 148 Exception: The request parameters are invalid in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 148 Call Stack: 0.0004 475296 1. {main}() /workspaces/bexio-stripe-pos-backend/www/bexio/test.php:0 0.0010 577696 2. BizCuit\BexioBills->search($query = class BizCuit\BXQuery\Bills { protected $allowedField = [0 => 'firstname_suffix', 1 => 'lastname_company', 2 => 'vendor_ref', 3 => 'currency_code', 4 => 'document_no', 5 => 'title', 6 => 'supplier_id', 7 => 'document_no', 8 => 'net_max', 9 => 'net_min', 10 => 'gross_max', 11 => 'gross_min', 12 => 'vendor', 13 => 'pending_amount_max', 14 => 'pending_amount_min', 15 => 'currency_code', 16 => 'title', 17 => 'vendor_ref', 18 => 'due_date_end', 19 => 'due_date_start', 20 => 'bill_date_end', 21 => 'bill_date_start', 22 => 'status']; protected $query = [0 => class stdClass { ... }] }, $offset = ???, $limit = ???) /workspaces/bexio-stripe-pos-backend/www/bexio/test.php:14 0.0010 578488 3. BizCuit\BexioCTX->fetch() /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:335 0.1734 580536 4. BizCuit\BexioCTX->handle_result($data = '{"message":"status: unsupported value type","error_code":400}', $code = 400, $type = 'application/json') /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:217 Nested Exceptions: Exception: {"message":"status: unsupported value type","error_code":400} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 148 Call Stack: The stack is empty or not available

**Comment by araeubig** [comment]
Your basic example is not working:

Fatal error: Uncaught Exception: {"message":"status: unsupported value type","error_code":400} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:148 Stack trace: #0 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(217): BizCuit\BexioCTX->handle_result('{"message":"sta...', 400, 'application/jso...') #1 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(335): BizCuit\BexioCTX->fetch() #2 /workspaces/bexio-stripe-pos-backend/www/bexio/test.php(14): BizCuit\BexioBills->search(Object(stdClass)) #3 {main} Next Exception: The request parameters are invalid in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 148 Exception: The request parameters are invalid in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 148 Call Stack: 0.0003 476440 1. {main}() /workspaces/bexio-stripe-pos-backend/www/bexio/test.php:0 0.0009 578840 2. BizCuit\BexioBills->search($query = class BizCuit\BXQuery\Bills { protected $allowedField = [0 => 'firstname_suffix', 1 => 'lastname_company', 2 => 'vendor_ref', 3 => 'currency_code', 4 => 'document_no', 5 => 'title', 6 => 'supplier_id', 7 => 'document_no', 8 => 'net_max', 9 => 'net_min', 10 => 'gross_max', 11 => 'gross_min', 12 => 'vendor', 13 => 'pending_amount_max', 14 => 'pending_amount_min', 15 => 'currency_code', 16 => 'title', 17 => 'vendor_ref', 18 => 'due_date_end', 19 => 'due_date_start', 20 => 'bill_date_end', 21 => 'bill_date_start', 22 => 'status']; protected $query = [0 => class stdClass { ... }] }, $offset = ???, $limit = ???) /workspaces/bexio-stripe-pos-backend/www/bexio/test.php:14 0.0009 579632 3. BizCuit\BexioCTX->fetch() /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:335 0.1506 581680 4. BizCuit\BexioCTX->handle_result($data = '{"message":"status: unsupported value type","error_code":400}', $code = 400, $type = 'application/json') /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:217 Nested Exceptions: Exception: {"message":"status: unsupported value type","error_code":400} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 148 Call Stack: The stack is empty or not available

**Comment by araeubig** [comment]
I get it working with a new approach on "list invoices" and will play around now.

Again: Your approach dealing with the bexio API is absolutely great - but your documentation is actually more for you than for another person :-)

**Comment by artnum** [comment]
Yes I haven't worked much on documentation, I am on the bexio api for something like two months and I haven't tested all the endpoints yet.
