### ISSUE TITLE
Trying to get a contact by ID

### ISSUE THREAD

**Issue by araeubig** [artnum/BizCuit-Bexio#3]
Sorry for disturbing you again:

I have actually no chance to get a contact by ID. The list of contacts works perfect but the "get" doesn't work -> I think that my approach is not correct:

```
$context = new BizCuit\BexioCTX($bexio_api_token);

$invoices = new BizCuit\BexioInvoice($context);
$contacts = new BizCuit\BexioContact($context);

$invoicesQuery = $invoices->newQuery();
$invoicesQuery->add('kb_item_status_id', '8');

$invoicesPending = $invoices->search($invoicesQuery);
foreach($invoicesPending as $invoice) {
    $client = $invoice->contact_id;
    $contact = $contacts->get($client);
}
```

It would be great to get a small hint.

Regards André and a happy Sunday from Basel.

**Comment by artnum** [comment]
It seems right too me.

What might be the problem here is that `$contacts->get($id)` works only for non-archived contact. That might be the problem, if you want to to have all contacts you want to use `$contact = $contacts->get($client, ['show_archived' => 'true']);`

**Comment by araeubig** [comment]
It doesn't work for normal contacts too. If you want i could you give my test API-key - that wouldn't be a problem.

**Comment by artnum** [comment]
Ok, there was an issue here. it should be fine now.

**Comment by araeubig** [comment]
Sorry for disturbing. I tried the getting again with:

```
<?php
require_once '../vendor/autoload.php';

$bexio_api_token = "xxxxx"
$bxCtx = new BizCuit\BexioCTX($bexio_api_token);

$contacts = new BizCuit\BexioContact($bxCtx);
$client = 41;
$contact = $contacts->get($client, ['show_archived' => 'true']);
print_r($contact);
```

and get following error:

`Fatal error: Uncaught Exception: {"error_code":404,"message":"Page not found"} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:151 Stack trace: #0 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(217): BizCuit\BexioCTX->handle_result('{"error_code":4...', 404, 'application/jso...') #1 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(497): BizCuit\BexioCTX->fetch() #2 /workspaces/bexio-stripe-pos-backend/www/bexio-v1/get.php(9): BizCuit\BexioContact->get(41, Array) #3 {main} Next Exception: The resource could not be found in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 151 Exception: The resource could not be found in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 151 Call Stack: 0.0003 478656 1. {main}() /workspaces/bexio-stripe-pos-backend/www/bexio-v1/get.php:0 0.0007 583736 2. BizCuit\BexioContact->get($id = 41, $options = ['show_archived' => 'true']) /workspaces/bexio-stripe-pos-backend/www/bexio-v1/get.php:9 0.0007 584160 3. BizCuit\BexioCTX->fetch() /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:497 0.2258 586200 4. BizCuit\BexioCTX->handle_result($data = '{"error_code":404,"message":"Page not found"}', $code = 404, $type = 'application/json') /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:217 Nested Exceptions: Exception: {"error_code":404,"message":"Page not found"} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 151 Call Stack: The stack is empty or not available`

What i'am doing wrong?
