### ISSUE TITLE
Some collected questions or only one example required

### ISSUE THREAD

**Issue by araeubig** [artnum/BizCuit-Bexio#4]
Hello and thanks for writing via WhatsApp.

To understand your way of doing the things it would be great to get some examples by you. The examples shouldn't be detailed the normal working code would even help.

- Getting a contact by ID
- Add a contact
- Add a quote
- Edit a quote

I think with these three examples i could translate it to allmost all required uses. But if you have more it would be absolutely great. What i can offer is to extend with pull requests all new things which i had to build and to help documenting.

My target is to build a configurable workflow from "calenso"->"bexio" and from "bexio"<->"stripe terminal for POS". In a second step a connect from a "standalone cardterminal"<->"bexio".

I have read your annotation about the bexio behavior and you are absolutely right. Actually i started opening one ticket for each inadequacy or bug.

Regards André and it would be great to ready by you.

**Comment by artnum** [comment]
Basically, the workflow to create/edit anything would be like : 

```php   
    $bxbill = new BizCuit\BexioBills($bxCtx);
    $object = $bxbill->new();
    $object->supplier_id = $supplierid;
    $object->vendor_ref = $vendorref;
    $object->contact_partner_id = 1;
    $object->bill_date = $date;
    $object->due_date = $dudate;
    $object->amount_man = $amount;
    $object->manual_amount = true;
    $object->currency_code = $currency;
    $object->item_net = true;
    $object->attachment_ids = [$file];
    $object->address = new stdClass();
    $object->address->lastname_company = $name;
    $object->address->type = 'COMPANY';
    $lines = new stdClass();
    $lines->position = 1;
    $lines->amount = $amount;
    $object->line_items = [$lines];
    $object->discounts = [];
    $ret = $bxbill->set($object);
```
Updating is quite similar, except you use use `$bxbill->update($object);`. Take note that the Bexio API is buggy, so if you fetch an object and update it directly, it might not work at all (I try to workaround in the library but  ...).

For getting any object by ID, the use of `$bxbill->get($id)` works. In some case, the ID is not the ID but the UUID, the documentation got that wrong most of the time, so it's a guessing game. But contacts are by ID, it should be fine. What I do is

```php
        try {
          $contact = $bxContact->get($id);
          /* ... */
        } catch (Exception $e) {
          /* try to get archived value */
          $contact = $bxContact->get($id, ['show_archived' => 'true']);
          /* ... */
        }
```

**Comment by araeubig** [comment]
Thanks a lot - will play with your example and will give feedback for each part where i run into problems.

Regards André

PS: And i you have some code with more example content it would be great.

**Comment by artnum** [comment]
Just on update. If you use `->update()` it should update only the property you pass (but randomly buggy). If you use `->set()` with an ID in the body, it would overwrite the object.

**Comment by artnum** [comment]
I have added some documentations. I will improve with time.
