### ISSUE TITLE
Error on creating quote

### ISSUE THREAD

**Issue by araeubig** [artnum/BizCuit-Bexio#5]
I tested with starting my planned document workflow and logical way through bexio by creating at first:

- a quote: and run into an error (added at the bottom here) that i need a project id - based on bexio API documentation the project id is not needed. In my workflow logic i haven't a project id because i create the project based on the first quote. if i add a project id for testing it works.

my code:
```
$bxCtx = new BizCuit\BexioCTX($bexio_api_token);

$bxquote = new BizCuit\BexioQuote($bxCtx);

$object = $bxquote->new();

$object->title = "test quote";
$object->contact_id = "8";
$object->user_id = "1";
//$object->project_id = "8";
$object->mwst_is_net = true;

$ret = $bxquote->set($object);
```

my errror without project_id:
`Fatal error: Uncaught Exception: {"error_code":422,"message":"The form could not be saved due to the following errors:","errors":["global: Unexpected extra form field named \"project_id\"."]} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:154 Stack trace: #0 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(217): BizCuit\BexioCTX->handle_result('{"error_code":4...', 422, 'application/jso...') #1 /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php(536): BizCuit\BexioCTX->fetch() #2 /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php(18): BizCuit\BexioQuote->set(Object(BizCuit\BXObject\Quote)) #3 {main} Next Exception: Could not save the entity in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 154 Exception: Could not save the entity in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 154 Call Stack: 0.0003 479688 1. {main}() /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php:0 0.0008 586456 2. BizCuit\BexioQuote->set($content = class BizCuit\BXObject\Quote { protected $changes = [0 => 'title', 1 => 'contact_id', 2 => 'user_id', 3 => 'mwst_is_net']; protected $content = class stdClass { public $title = 'test neu 2'; public $contact_id = '8'; public $contact_sub_id = NULL; public $user_id = '1'; public $project_id = NULL; public $language_id = NULL; public $bank_account_id = NULL; public $currency_id = NULL; public $payment_type_id = NULL; public $header = NULL; public $footer = NULL; public $mwst_type = NULL; public $mwst_is_net = TRUE; public $show_position_taxes = NULL; public $is_valid_from = NULL; public $is_valid_until = NULL; public $delivery_address_type = NULL; public $api_reference = NULL; public $viewed_by_client_at = NULL; public $kb_terms_of_payment_template_id = NULL; public $template_slug = NULL; public $positions = NULL } }) /workspaces/bexio-stripe-pos-backend/www/bexio-v1/new.php:18 0.0008 587104 3. BizCuit\BexioCTX->fetch() /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:536 0.2167 588440 4. BizCuit\BexioCTX->handle_result($data = '{"error_code":422,"message":"The form could not be saved due to the following errors:","errors":["global: Unexpected extra form field named \\"project_id\\"."]}', $code = 422, $type = 'application/json') /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php:217 Nested Exceptions: Exception: {"error_code":422,"message":"The form could not be saved due to the following errors:","errors":["global: Unexpected extra form field named \"project_id\"."]} in /workspaces/bexio-stripe-pos-backend/www/vendor/artnum/bizcuit-bexio/bexio.php on line 154 Call Stack: The stack is empty or not available`

**Comment by araeubig** [comment]
If i comment out the "project_id"

```
class Quote extends BXObject {
    const NR = 'document_nr';
    const createProperties = [
        'title',
        'contact_id',
        'contact_sub_id',
        'user_id',
        //'project_id',
        'language_id',
        'bank_account_id',
        'currency_id',
        'payment_type_id',
        'header',
        'footer',
        'mwst_type',
        'mwst_is_net',
        'show_position_taxes',
        'is_valid_from',
        'is_valid_until',
        'delivery_address_type',
        'api_reference',
        'viewed_by_client_at',
        'kb_terms_of_payment_template_id',
        'template_slug',
        'positions'
    ];
}
```
it works without adding an id in the quote creation. Perhaps it depends on the other name in the API documentation ("pr_project_id") but if i define an id it will be created right with the "wrong" name.

**Comment by artnum** [comment]
It's a naming error in fact. And as it is not required, better remove it.
