### ISSUE TITLE
Avoid duplicated contacts

### ISSUE THREAD

**Issue by araeubig** [artnum/BizCuit-Bexio#7]
It would be great to use an automatically function like:

add contact (duplicate: no; merge: yes)

The contact would be added only if it doesn't exist and id new contact details are given they are merged into the original one.
Only an idea for integration.

**Comment by artnum** [comment]
You would like to match the contact name with a contact name already in the database and if the match is positive just update the contact ?

I guess it could be useful but doesn't belong to the project as the goal is to provide access to the data and not do automatic processing of the data. We can create a project that extends this one to have those kind of features (like searching an invoice by project_id) or re-conciliate contacts.

In fact I might create that project soon as I start to accumulate quite some code around Bexio API.

**Comment by araeubig** [comment]
Yes you are absolutely right - this should be for the API only. It would be perfect to create a new one with additional functions and make use of the real API calls from this one. Actually i'am writing the basic concept which functions i have to use und how they should work. I will write it until end of the weekend.

Have a nice evening André
