### ISSUE TITLE
Diving into the classes and trying to use ContactGroups

### ISSUE THREAD

**Issue by araeubig** [artnum/BizCuit-Bexio#8]
I need only a small hint to search in ContactGroups before adding "wrong" code. I saw that ContactGroups exist with ROOObject but with the normal: `$bxcontactgroup = new BizCuit\BexioContactGroup($bxCtx);` it doesn't work.

**Comment by artnum** [comment]
Most of the classes set like `class ContactGroup extends ROObject { }` are stuff I haven't had time to look for. So there is no `BizCuit\BexioContactGroup` class yet.

I guess the class would look like, in bexio.php
```php
class BexioContactGroup extends BexioAPI {
	const type = 'contact_group';
	protected string $className = 'BizCuit\BXObject\ContactGroup';
	protected string $query = 'BizCuit\BXQuery\ContactGroup';


	use tBexioV2Api, tBexioObject, tBexioCollection;
}
```

And the object class, in bxobject.php, would be like
```php
class ContactGroup extends BXObject {
    const NR = null;
    const createProperties = [
        'name'
    ];
}
```

See if the pull request works for you  and then I can merge into master.

And for the search class, in bxquery.php, would be like 
```php
class ContactGroup extends BXQuery {
	function __construct() {
		parent::__construct([
			'name'
		]);
	}
}
```
